file <- "./data/household_power_consumption.txt"
hdata <-read.csv2(file, header = TRUE, sep = ";",stringsAsFactors=FALSE)
hdata2 <- subset(hdata,Date == "1/2/2007" | Date == "2/2/2007")
hdata2[,1] <- as.Date(hdata2[,1],'%d/%m/%Y')
hdata2[,2] <- hdata2[,2]
hdata2[,3] <- as.numeric(hdata2[,3])
hdata2[,4] <- as.numeric(hdata2[,4])
hdata2[,5] <- as.numeric(hdata2[,5])
hdata2[,6] <- as.numeric(hdata2[,6])
hdata2[,7] <- as.numeric(hdata2[,7])
hdata2[,8] <- as.numeric(hdata2[,8])
hdata2[,9] <- as.numeric(hdata2[,9])
datetime <- as.POSIXct(strptime(paste(hdata2[,1],hdata2[,2]), "%Y-%m-%d %H:%M:%S"))
weekday <- as.character(format(datetime,"%a"))
hdata3 <- cbind(hdata2,datetime,weekday)
png(bg = "white", filename = "plot3.png",width = 480,height = 480 )
with(hdata3,plot(datetime,Sub_metering_1,ylab="Energy sub metering",type="n",xlab=""))
par(new=T)
with(hdata3, lines(datetime, Sub_metering_1, col = "black"))
with(hdata3, lines(datetime, Sub_metering_2, col = "red"))
with(hdata3, lines(datetime, Sub_metering_3, col = "blue"))
legend("topright",cex=0.7, lty = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()
